version: '3.9'
services:
  php-fpm:
    build: ./.config/docker/php
    container_name: php81
    volumes:
      - ./:/var/www/html
      - ./.config/docker/php/jit.ini:/usr/local/etc/php/conf.d/jit.ini
      - ./.config/docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini


  nginx:
    image: nginx:1.19.6
    container_name: nginx-example-php81
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./.config/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  redis:
    image: redis:latest
    container_name: redis-server

  memcached:
    image: memcached:latest
    container_name: memcached-server