name: "Release Tag"

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get last commit from release branch
        run: |
          git fetch origin refs/heads/release/*.*.*:refs/remotes/origin/release/*.*.*
          release_commit=$(git rev-list --max-count=1 origin/release/*.*.*)
          git checkout $release_commit
          echo "::set-output name=release_commit::$release_commit"

      - name: Create tag
        if: success()
        run: |
          release_commit=${{ steps.release.outputs.release_commit }}
          tag="v${{ github.run_number }}"
          git tag $tag $release_commit
          git push origin $tag

      - name: Delete release branch
        if: success()
        run: |
          git push origin --delete release/*.*.*