name: Generate tag and release notes

on:
  pull_request_review_comment:
    branches: [ master ]
    paths:
      - '**/release/*.*.*'
    comment_body:
      - delivered
jobs:
  generate-release-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Obter nome da tag
        id: get_tag_name
        run: |
          branch_name=${{ github.event.pull_request.head.ref }}
          tag_name=$(echo $branch_name | cut -d'/' -f 2-)
          echo "::set-output name=tag_name::$tag_name"

      - name: Criar tag de lançamento
        uses: actions/create-release@v3
        with:
          tag_name: ${{ steps.get_tag_name.outputs.tag_name }}
          release_name: ${{ steps.get_tag_name.outputs.tag_name }}
          body: |
            Este lançamento foi gerado automaticamente a partir da branch ${{ steps.get_tag_name.outputs.tag_name }}.

  generate-release-notes:
    runs-on: ubuntu-latest
    needs: [ generate-release-tag ]
    steps:
      - uses: actions/checkout@v3

      - name: Gerar notas de versão
        id: generate_release_notes
        run: |
          branch_name=${{ github.event.pull_request.head.ref }}
          tag_name=$(echo $branch_name | cut -d'/' -f 2-)
          release_notes=$(git log --pretty=format:"* %s" $tag_name..master)
          echo "::set-output name=release_notes::$release_notes"

      - name: Atualizar notas de versão do lançamento
        uses: actions/update-release-notes@v3
        with:
          tag_name: ${{ steps.get_tag_name.outputs.tag_name }}
          release_body: ${{ steps.generate_release_notes.outputs.release_notes }}