name: Release Tag

on:
  push:
    branches:
      - master

jobs:
  release:
    if: startsWith(github.event.pull_request.head.ref, 'release/') && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get release branch name
        run: |
          branch=$(echo "${{ github.event.pull_request.head.ref }}" | cut -d '/' -f 2-)
          echo "::set-output name=release_branch::$branch"

      - name: Get release commit
        run: |
          branch=${{ steps.release.outputs.release_branch }}
          commit=$(git log --pretty=format:%H -1 "refs/heads/release/$branch")
          echo "::set-output name=release_commit::$commit"

      - name: Create tag
        run: |
          branch=${{ steps.release.outputs.release_branch }}
          commit=${{ steps.release.outputs.release_commit }}
          tag="v${branch}"
          git tag $tag $commit
          git push origin $tag