name: Testes e Cobertura de Código

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_REGISTRY_URL: registry.hub.docker.com
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  testes-e-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Print Environment Variables
        run: |
          echo "## Environment Variables"
          echo "DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}"
          echo "DOCKER_USERNAME: ${DOCKER_USERNAME}"

      - name: Authenticate to Docker Registry
        run: |
          echo $DOCKER_PASSWORD |  docker login --username $DOCKER_USERNAME --password-stdin $DOCKER_REGISTRY_URL

      - name: Pull Custom Image
        run: |
          docker pull $DOCKER_REGISTRY_URL/$DOCKER_USERNAME/php:build-8.1

      - name: Set up custom Docker environment
        run: |
          docker run --rm \
            -e XDEBUG_MODE=coverage \
            -v $PWD:/app \
            $DOCKER_REGISTRY_URL/$DOCKER_USERNAME/php:build-8.1

      - name: Instalar Dependências
        run: composer install

      - name: Executar Testes Unitários
        run: vendor/bin/phpunit --testdox

      - name: Gerar Cobertura de Código
        run: vendor/bin/phpunit --coverage-text=./app/report/coverage.txt

      - name: Upload de Artefato de Cobertura
        uses: actions/upload-artifact@v3
        with:
          name: coverage.txt
          path: ./app/report/